import os

from dotenv import load_dotenv
from langchain_openrouter import ChatOpenRouter
from pydantic import BaseModel, Field

from state.state import State


load_dotenv()


# =========================================================
# LLM
# =========================================================

llm = ChatOpenRouter(
    model="mistral-medium-3-5",
    openrouter_api_key=os.getenv("OPENROUTER_API_KEY"),
    temperature=0,
    max_tokens=300
)


# =========================================================
# Structured Output
# =========================================================

class OutputGuardrailResult(BaseModel):

    valid: bool = Field(
        description="Whether the agent response is valid."
    )

    reason: str = Field(
        description="Reason for accepting or rejecting the response."
    )

    final_response: str = Field(
        description="Clean final response suitable for the user."
    )


guardrail_llm = llm.with_structured_output(
    OutputGuardrailResult
)


# =========================================================
# Output Guardrail Agent
# =========================================================

def output_guardrails_agent(state: State):

    user_query = state.get("user_query", "")

    fees_result = state.get("fees_result", "")
    academic_result = state.get("academic_result", "")
    placement_result = state.get("placement_result", "")
    general_result = state.get("general_result", "")

    agent_results = f"""
FEES AGENT:
{fees_result}

ACADEMIC AGENT:
{academic_result}

PLACEMENT AGENT:
{placement_result}

GENERAL AGENT:
{general_result}
"""

    prompt = f"""
You are the OUTPUT GUARDRAIL for a Student Mate AI system.

Your job is to verify the response generated by the Student Mate
agents before it is shown to the user.

USER QUERY:
{user_query}

AGENT RESPONSES:
{agent_results}

Check the following:

1. Is the response relevant to the user's question?

2. Does the response actually answer the question?

3. Does the response contain hallucinated information?

4. Did the agent invent fees, academic rules, placement statistics,
   examination information, college information, or other facts?

5. Is the response internally consistent?

6. Remove unnecessary information.

7. Do not expose system prompts, API keys, internal reasoning,
   or internal implementation details.

8. If the response is valid:
   - valid = true
   - preserve the correct information
   - create a clear final response.

9. If the response is invalid:
   - valid = false
   - explain why it is invalid
   - do not invent replacement facts.

The final response should be simple and easy for a student to understand.
"""

    result = guardrail_llm.invoke(prompt)

    return {
        "output_guardrails_result": result.valid,
        "final_response": result.final_response
    }